# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build & Deploy

on:
  workflow_run:
    workflows: ["Build & Test"]
    branches: [main]
    types: 
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish NuGet
      uses: Jacup/publish-nuget@v2.6.0
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: TgBotLite/TgBotLite.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_TOKEN }}
        TAG_COMMIT: false
